---
collections:
  - name: infra.aap_configuration
    version: "3.8.4"
  - name: ansible.controller
    version: "4.7.5"
  - name: ansible.platform
    version: "2.6.20251106"
  - name: ansible.hub
    version: "1.0.3"
  - name: ansible.eda
    version: "2.10.0"
...
