---
# Custom Credential Types
# Using _all suffix for wildcard merging
# Reference: https://github.com/redhat-cop/aap_configuration_template

controller_credential_types_all:
  - name: HashiCorp Vault Secret Lookup
    description: Credentials for HashiCorp Vault secret lookups
    kind: cloud
    inputs:
      fields:
        - id: vault_url
          type: string
          label: Vault Server URL
          help_text: The URL of the Vault server (e.g., https://vault.example.com:8200)
        - id: vault_token
          type: string
          label: Vault Token
          secret: true
          help_text: Vault authentication token
        - id: vault_namespace
          type: string
          label: Namespace
          help_text: Vault namespace (optional, for Vault Enterprise)
        - id: vault_cacert
          type: string
          label: CA Certificate
          multiline: true
          help_text: CA certificate for TLS verification (optional)
      required:
        - vault_url
        - vault_token
    injectors:
      env:
        VAULT_ADDR: !unsafe "{{ vault_url }}"
        VAULT_TOKEN: !unsafe "{{ vault_token }}"
        VAULT_NAMESPACE: !unsafe "{{ vault_namespace | default('') }}"
        VAULT_CACERT: !unsafe "{{ vault_cacert | default('') }}"
      extra_vars:
        vault_addr: !unsafe "{{ vault_url }}"
        vault_token: !unsafe "{{ vault_token }}"
        vault_namespace: !unsafe "{{ vault_namespace | default('') }}"

