---
# QA Environment Inventory Hosts
# Using _qa suffix for wildcard merging

controller_hosts_qa:
  - name: localhost
    description: Local execution
    inventory: QA Localhost
    variables:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3

