---
# QA Environment Job Templates
# All using wildcard suffixes for consistent merging

controller_job_templates_qa:
  - name: Example Hello World
    description: Simple hello world job for testing
    job_type: run
    organization: Default
    inventory: QA Localhost
    project: Example Ansible Collection
    playbook: playbooks/hello_world.yml
    execution_environment: Web EE (QA)
    ask_variables_on_launch: true
    verbosity: 0  # Less verbose in QA

controller_job_templates_qa_web:
  - name: Deploy Web Application (QA)
    description: Deploys web application to QA environment
    job_type: run
    organization: Applications
    inventory: QA Servers
    project: Platform Automation
    playbook: playbooks/deploy_web_app.yml
    execution_environment: Web EE (QA)
    credentials:
      - QA SSH Key
    ask_variables_on_launch: false  # Stricter in QA
    extra_vars:
      app_environment: qa
      app_version: "{{ app_version | default('stable') }}"

controller_job_templates_qa_validation:
  - name: QA Validation Tests
    description: Runs validation tests in QA
    job_type: run
    organization: Default
    inventory: QA Servers
    project: Platform Automation
    playbook: playbooks/validate_qa.yml
    execution_environment: Default Execution Environment

