---
# QA Environment Projects
# Versions locked by release manifest
# All using wildcard suffixes for consistent merging

controller_projects_qa:
  - name: Example Ansible Collection
    description: Example automation collection
    organization: Default
    scm_type: git
    scm_url: https://github.com/djdanielsson/rh1-custom-collection.git
    scm_branch: "{{ collection_version | default('main') }}"  # Locked by release manifest
    scm_update_on_launch: false  # Don't auto-update in QA
    scm_delete_on_update: true
    credential: QA GitHub Token
    default_environment: Web EE (QA)

controller_projects_qa_platform:
  - name: Platform Automation
    description: Infrastructure and platform playbooks
    organization: Platform
    scm_type: git
    scm_url: https://github.com/example/platform-automation.git
    scm_branch: "{{ platform_version | default('main') }}"
    scm_update_on_launch: false
    default_environment: Default Execution Environment

