---
# Dev Environment Credentials
# Note: Never put actual secrets here! Reference environment variables
# which are populated by Tekton pipeline from OCP secrets
# Using _dev suffix for wildcard merging

controller_credentials_dev:
  - name: Dev GitHub Token
    description: GitHub access for dev environment
    organization: Default
    credential_type: Source Control
    inputs:
      username: "{{ lookup('env', 'GITHUB_USERNAME') | default('git') }}"
      password: "{{ lookup('env', 'GITHUB_TOKEN') | default('') }}"
  
  - name: Dev SSH Key
    description: SSH key for dev servers
    organization: Platform
    credential_type: Machine
    inputs:
      username: ansible
      ssh_key_data: "{{ lookup('env', 'SSH_PRIVATE_KEY') | default('') }}"

